### PR TITLE
JSON error messages

### PR DESCRIPTION
**Pull request by asoffer**
Gets json output from the interpreter when error messages are written.
Lays them out in html/css.

### CODE REVIEW

**Review by perimosocordiae — APPROVED** [review]
Very nice! I was planning to add a more structured output option for the LSP tooling, and you beat me to it.

**Comment by perimosocordiae** [comment]
I ended up rewriting the display logic a bit. It turns out that we still emit ANSI color codes in some error message bodies, so I had to revive the unescaping hack.

This also turned up a bug in the interpreter where parse failures were being ignored (because the Parse function would return an empty vector of nodes, which is equivalent to an empty file).

**Comment by asoffer** [comment]
I know where the ANSI is coming from. I intend to remove it.

**Comment by asoffer** [comment]
ANSI codes are now restricted to --diagnostic=console, as of https://github.com/asoffer/Icarus/commit/d115de5f3e6fb16ae20dcee7ef3bf199c011df26

**Pull request merged**
